; ─── Xdebug Config ──────────────────────────────────────────────────────────
[xdebug]
xdebug.mode                = ${XDEBUG_MODE:-develop,debug}
xdebug.start_with_request  = yes
xdebug.client_host         = ${XDEBUG_CLIENT_HOST:-host.docker.internal}
xdebug.client_port         = ${XDEBUG_CLIENT_PORT:-9003}
xdebug.idekey              = VSCODE
xdebug.max_nesting_level   = 512
xdebug.log                 = /var/log/php/xdebug.log
xdebug.log_level           = 0
